compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  zero_stage: 3
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
distributed_type: DEEPSPEED
main_training_function: main
mixed_precision: bf16
machine_rank: {rank}
main_process_ip: {leader_ip}
main_process_port: {leader_port}
num_machines: {num_nodes}
num_processes: 24
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
